dist: trusty
os: linux

language: node_js
node_js:
  - '14'

branches:
  only:
  - master
  - development

addons:
  chrome: stable

before_script:
  - cd ./text-adventure-sama/
  - npm install -g @angular/cli

install:
  - npm install

script:
  - ng lint
  - npm run test-ci