dist: trusty
os: linux

language: node_js
node_js:
  - '12'

branches:
  only:
  - master
  - development

addons:
  chrome: stable

cache:
  directories:
    - ./text-adventure-sama/node_modules

install:
  - npm install

script:
  - ng lint
  - npm test-ci